[tool.poetry]
name = "sudoku_checker"
version = "0.1.0"
description = "Code challenger"
authors = ["Carlo1911"]

[tool.poetry.dependencies]
python = "y"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
