import pytest

from main import matrix_challenge


@pytest.mark.parametrize(
    "input, expected",
    [
        (
            [
                "(1,2,3,4,5,6,7,8,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(6,x,5,x,3,x,x,4,x)",
                "(2,x,1,5,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,8)",
            ],
            "legal",
        ),
        (
            [
                "(1,2,3,4,5,6,7,8,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(6,x,5,x,3,x,x,4,x)",
                "(2,x,1,5,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,4)",
                "(9,1,2,3,4,5,6,7,8)",
            ],
            "legal",
        ),
        (
            [
                "(1,2,3,4,5,6,7,8,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(6,x,5,x,3,x,x,4,x)",
                "(2,x,1,1,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,9)",
            ],
            "3,4,5,9",
        ),
        (
            [
                "(1,2,3,4,5,6,7,8,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(6,x,5,x,3,x,x,4,x)",
                "(2,x,1,1,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
            ],
            "4,5",
        ),
        (
            [
                "(1,2,3,4,5,6,7,8,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(6,x,5,x,3,x,x,4,x)",
                "(2,x,1,5,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,9)",
                "(9,1,2,3,4,5,6,7,8)",
            ],
            "3,9",
        ),
        (
            [
                "(1,2,3,4,5,6,7,8,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(6,x,5,x,3,x,x,4,x)",
                "(2,x,1,5,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,9)",
                "(x,x,x,x,x,x,x,x,x)",
                "(x,x,x,x,x,x,x,x,9)",
                "(9,1,2,3,4,5,6,7,8)",
            ],
            "3,6,9",
        ),
    ],
)
def test_matrix_challenge(input, expected):
    assert matrix_challenge(input) == expected
